# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "vmd" "nvme" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5f56a1bd-1490-4988-b07b-95101c9c279a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5f56a1bd-1490-4988-b07b-95101c9c279a".device = "/dev/disk/by-uuid/5f56a1bd-1490-4988-b07b-95101c9c279a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1C0B-78B5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media/usb-drive" =
    { device = "/dev/disk/by-uuid/010E-0E4C";
      fsType = "exfat";
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ca79c9d0-98a3-4ea8-b683-c13bf0796604"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
